export const PROBLEM_TITLE_CHANGE = 'PROBLEM_TITLE_CHANGE'

export const PROBLEM_DESCRIPTION_CHANGE = 'PROBLEM_DESCRIPTION_CHANGE'

export const PROBLEM_DIFFICULTY_CHANGE = 'PROBLEM_DIFFICULTY_CHANGE'

export const PROBLEM_EDITORIAL_CHANGE = 'PROBLEM_EDITORIAL_CHANGE'
